config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks
  has_many :movies, through: :bookmarks, :dependent => :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list_id = @list.id
    @bookmark.movie_id = params[:bookmark][:movie_id].to_i
    if @bookmark.save
      redirect_to list_path(@bookmark.list_id)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list_id)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @movie, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.input :movie_id, collection: Movie.all %>
  <%= f.submit "Submit this Bookmark", class: "btn btn-primary" %>
<% end %>

app/views/bookmarks/create.html.erb
create.html.erb

app/views/bookmarks/destroy.html.erb
destroy.html.erb

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Add a New Bookmark</h1>
  <%= render 'bookmarks/form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit this List!", class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
<% render 'shared/navbar' %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.bathindalive.in/wp-content/uploads/2017/04/bathinda-city-guide-bathidalive.in-bathinda-movies.jpg);">
  <div class="container">
    <h1>Curated Movie Lists</h1>
    <p>For Movie Lovers, by Movie Lovers</p>
  </div>
</div>

<div class="container">
  <h3>All Lists</h3>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : image_path("https://bellyfull.net/wp-content/uploads/2019/09/Perfect-Stovetop-Popcorn-blog-2-500x500.jpg") %>)">
        <%= link_to "", list_path(list), class: "card-link" %>
        <p><%= list.name %></p>
      </div>
    <% end %>
  </div>
  <%= link_to "Create a New Movie List", new_list_path, class: "btn btn-primary" %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Add a New Movie List</h1>
  <%= render 'lists/form' %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= List.find(params[:id]).name %></h1>
  <h3>All Movies</h3>
  <ul>
    <% @list.bookmarks.each do |bookmark| %>
      <li>
        <div>
          <%= image_tag Movie.find(bookmark.movie_id).poster_url, alt: "alttext" %>
          <p><%= bookmark.comment %></p>
          <%= link_to "Delete this movie", bookmark_path(bookmark), method: :delete, data: { confirm: "Delete #{Movie.find(bookmark.movie_id).title}?"} %>
        </div>
      </li>
    <% end %>
  </ul>
  <p class="link"><%= link_to "Add a New Bookmark", new_list_bookmark_path(params[:id]) %></p>
  <p class="link"><%= link_to "Back to All Lists", lists_path %></p>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">Watch List</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", lists_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Create a List", new_list_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>